online_market/online_market/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from users.urls import reset_password


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('', include(reset_password)),
    path('', include('users.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

online_market/shop/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static

from . import views

app_name = 'shop'

cart_path = [
    path('cart', views.CartView.as_view(), name='cart_detail'),
    path('add/<product_id>/',
         views.AddProductToCartView.as_view(), name='cart_add'),
    path('update/<product_id>/',
         views.CartProductQuantityUpdateView.as_view(), name='cart_update'),
    path('remove/<product_id>/',
         views.CartProductQuantityDecreaseView.as_view(), name='cart_remove'),
    path('cart/clear/', views.ClearCartView.as_view(), name='cart_clear'),
]

order_path = [
    path('order/create/', views.OrderCreateView.as_view(),
         name='order_create'),
    path('order/created/', views.OrderCreatedView.as_view(),
         name='order_created'),
    path('order/<order_id>/', views.OrderDetailView.as_view(),
         name='order_detail'),
]

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('catalog', views.CatalogView.as_view(), name='catalog'),
    path('product/<slug>/', views.ProductDetailView.as_view(),
         name='product_detail'),
    path('about_us', views.AboutUsView.as_view(), name='about_us'),
    path('', include(cart_path)),
    path('', include(order_path)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

online_market/users/urls.py
from django.contrib.auth.views import (LogoutView, PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)
from django.urls import include, path, reverse_lazy

from . import views

app_name = 'users'

reset_password = [
    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html'),
        name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete')
]

auth = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('register_done/', views.RegisterDone.as_view(), name='register_done'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
]

profile = [
    path('profile/<str:username>/', views.ProfileView.as_view(),
         name='profile'),
    path('profile/<str:username>/edit/', views.ProfileEditView.as_view(),
         name='profile_edit'),
]

urlpatterns = [
    path('', include(auth)),
    path('', include(profile)),
    path('reset_password/', include(reset_password)),
]

online_market/shop/forms.py
from django import forms

from .models import Order

# генератор для добавления товара в количестве от 1 до 20
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    """форма для добавления товара в корзину"""
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int, label='Количество')
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)


class OrderForm(forms.ModelForm):
    """форма оформления заказа"""
    first_name = forms.CharField(
        label='Имя',
        max_length=50,
        widget=forms.TextInput(attrs={'placeholder': 'Иван'}))

    last_name = forms.CharField(
        label='Фамилия',
        max_length=50,
        widget=forms.TextInput(attrs={'placeholder': 'Иванов'}))

    phone_number = forms.CharField(
        label='Номер телефона',
        max_length=50,
        widget=forms.TextInput(attrs={'placeholder': '+79781234567'}))

    city = forms.CharField(
        label='Город',
        max_length=50,
        widget=forms.TextInput(attrs={'placeholder': 'Москва'}))

    address = forms.CharField(
        label='Адрес',
        max_length=50,
        widget=forms.TextInput(attrs={'placeholder': 'Красная площадь'}))

    postal_code = forms.CharField(
        label='Почтовый индекс',
        max_length=6,
        widget=forms.TextInput(attrs={'placeholder': '230035'}))

    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'phone_number',
                  'city', 'address', 'postal_code')

online_market/shop/views.py
from typing import Any
from django.conf import settings
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import (CreateView, DeleteView, DetailView,
                                  ListView, UpdateView)
from django.views.generic.base import TemplateView
from shop.forms import CartAddProductForm, OrderForm
from shop.models import Cart, CartItem, Example, Order, OrderItem, Product
from users.models import CustomUser


class IndexView(ListView):
    template_name = 'shop/index.html'
    context_object_name = 'image_for_example'
    queryset = Example.objects.all()


@method_decorator(cache_page(60), name='get')
class CatalogView(ListView):
    template_name = 'shop/catalog.html'
    context_object_name = 'product'
    queryset = Product.objects.all()
    paginate_by = settings.PRODUCT_COUNT


class ProductDetailView(DetailView):
    model = Product
    template_name = 'shop/product_detail.html'
    queryset = Product.objects.all()

    def get_object(self, queryset=None):
        slug = self.kwargs.get('slug')
        return get_object_or_404(self.queryset, slug=slug, available=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            cart = Cart.objects.get(user=self.request.user)
            context['product_in_cart'] = cart.has_product(self.get_object())
        context['cart_product_form'] = CartAddProductForm()
        return context


@method_decorator(cache_page(60*60), name='dispatch')
class AboutUsView(TemplateView):
    template_name = 'shop/about_us.html'


class CartView(LoginRequiredMixin, ListView):
    template_name = 'shop/cart.html'
    paginate_by = settings.PRODUCT_COUNT

    def get_queryset(self):
        try:
            cart = Cart.objects.prefetch_related(
                'cartitem_set__product').get(user=self.request.user)
        except Cart.DoesNotExist:
            cart = Cart.objects.create(user=self.request.user)
        return CartItem.objects.filter(cart=cart).order_by('product__name')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_items = self.get_queryset()
        total_price = sum(item.get_total_price() for item in cart_items)
        paginator = Paginator(cart_items, self.paginate_by)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['total_price'] = total_price
        context['cart_items'] = page_obj
        return context


class AddProductToCartView(CreateView):
    model = CartItem
    fields = ['quantity']
    success_url = reverse_lazy('shop:cart_detail')

    def form_valid(self, form):
        cart = Cart.objects.get(user=self.request.user)
        product = get_object_or_404(Product, id=self.kwargs['product_id'])
        form.instance.cart = cart
        form.instance.product = product
        return super().form_valid(form)


class CartProductQuantityUpdateView(UpdateView):
    def get(self, request, *args, **kwargs):
        product_id = self.kwargs.get('product_id')
        item_cart = CartItem.objects.get(product_id=product_id)
        item_cart.update_quantity()
        return redirect('shop:cart_detail')


class CartProductQuantityDecreaseView(UpdateView):
    def get(self, request, *args, **kwargs):
        product_id = self.kwargs.get('product_id')
        item_cart = CartItem.objects.get(product_id=product_id)
        item_cart.decrease_quantity()
        return redirect('shop:cart_detail')


class ClearCartView(LoginRequiredMixin, DeleteView):
    model = Cart
    template_name = 'shop/cart.html'
    success_url = reverse_lazy('shop:cart_detail')

    def get_object(self, queryset=None):
        return Cart.objects.get(user=self.request.user)

    def delete(self, request, *args, **kwargs):
        cart = self.get_object()
        cart.cartitem_set.all().delete()
        return self.get(request, *args, **kwargs)


class OrderCreateView(LoginRequiredMixin, CreateView):
    model = Order
    template_name = 'shop/order_create.html'
    form_class = OrderForm
    success_url = reverse_lazy('shop:order_created')

    def get_initial(self):
        initial_dict = {
            'first_name': self.request.user.first_name,
            'last_name': self.request.user.last_name,
            'phone_number': self.request.user.phone_number,
            'city': self.request.user.city,
            'address': self.request.user.address,
            'postal_code': self.request.user.postal_code
        }
        return initial_dict

    def get_queryset(self):
        cart_items = CartItem.objects.select_related(
            'product').prefetch_related(
            'cart').filter(cart__user=self.request.user)
        return cart_items

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_items = self.get_queryset()
        total_price = sum(item.get_total_price() for item in cart_items)
        context['total_price'] = total_price
        context['item_in_order'] = cart_items
        return context

    def form_valid(self, form):
        order = form.save(commit=False)
        order.user = self.request.user
        order.email = self.request.user.email
        order.save()
        cart_items = self.get_queryset()
        for item in cart_items:
            OrderItem.objects.create(
                order=order,
                product=item.product,
                price=item.product.price,
                quantity=item.quantity)
        cart_items.delete()
        orders = self.request.user.orders_count + 1
        CustomUser.objects.filter(
            email=self.request.user.email).update(orders_count=orders)
        return super().form_valid(form)


class OrderCreatedView(LoginRequiredMixin, TemplateView):
    template_name = 'shop/order_created.html'


class OrderDetailView(DetailView):
    model = OrderItem
    template_name = 'shop/order_detail.html'
    queryset = OrderItem.objects.all()

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_anonymous:
            return redirect(reverse('shop:catalog'))
        current_order = self.get_object()
        if current_order.user != self.request.user:
            return redirect(reverse('users:profile',
                                    args=(request.user.username,)))
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        order_id = self.kwargs.get('order_id')
        return get_object_or_404(Order, id=order_id,)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_order = self.get_object()
        order_item = OrderItem.objects.filter(order=current_order).all()
        context['order_item'] = order_item
        context['current_order'] = current_order
        return context

online_market/templates/shop/about_us.html
{% extends 'base.html' %}
{% load static %}
{% block title %} О нас {% endblock %}
{% block content %}
  <h2><p class="name">Какое-то текстовое оформление </p></h2>
{% endblock %}

online_market/templates/shop/cart.html
{% extends "base.html" %}
{% load static %}
{% block title %} Корзина {% endblock %}
{% block content %}
<div class="main_page">
  <div class="row">
  {% if cart_items|length < 1 %}
  <div class="index_title">
    <p> Ваша корзина пустая </p>
    <p> <a href="{% url "shop:catalog" %}" class="nav__link"> Посмотреть товар </a> </p>
  </div>
  {% else %}
    <div class="index_title">
      Ваш товар в корзине:
    </div>
    {% for item in cart_items %}
      <div class="column">
        <img src="{{ item.product.image.url }}" class="border">
        <p> <b> Название: </b> {{ item.product.name }} </p>
        <p> <b>Количество товара в корзине: </b>{{ item.quantity }} </p>
        <p>
          <a href="{% url 'shop:cart_update' item.product.id %}" class="nav__link">Добавить</a>
          {% if item.quantity > 1%}
          <a href="{% url "shop:cart_remove" item.product.id %}" class="nav__link">Убавить</a>
          {% else %}
          <a href="{% url "shop:cart_remove" item.product.id %}" class="nav__link">Удалить</a>
          {% endif %}
        </p>
        <div class="header__inner">
          <p> Цена товара: {{ item.product.price }} </p>
          <p>
            {% if  item.quantity == 1 %}
              Цена за {{item.quantity}} свечу {{ item.get_total_price }} 
            {% elif  item.quantity <= 4 %}
              Цена за {{item.quantity}} свечи: {{ item.get_total_price }}
            {% elif item.quantity >= 5%}
              Цена за {{item.quantity}} свечей: {{ item.get_total_price }}
            {%endif%}
          </p>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
<div class="total_cart">
  <a href="{% url 'shop:cart_clear' %}" class="text" onclick="event.preventDefault(); document.getElementById('cart-clear-form').submit();">Очистить корзину</a>
    <form id="cart-clear-form" method="post" action="{% url 'shop:cart_clear' %}">
      {% csrf_token %}
    </form>
  <p> Итоговая цена: {{ total_price }} рублей </p>
  <a href="{% url "shop:order_create" %}" class="text"> Оформить заказ </a>
  <a href="{% url "shop:catalog" %}" class="text"> Вернуться в каталог </a>
</div>
{% endif %}

{% if is_paginated %}
{% include 'includes/paginator.html' %}
{% endif %}

{% endblock %}

online_market/templates/shop/catalog.html
{% extends 'base.html' %}
{%load static%}
{% load cache %}
{% block title %} Каталог {% endblock %}
{%block content%}
  <div class="main_page">
    <div class="row">
        {%for product in product%}
          <div class="product__column">
              <img src="{{ product.image.url }}" class="border">
              <p> <b>{{ product.name }} </b> </p>
              <p class="cat_name"> <b>Цена:</b> {{ product.price }} рублей </p>
              <p> <b>Описание</b>: {{product.description}}</p>
              <p> <a class="product__text" href="{{ product.get_absolute_url }}"> Подробное описание </a> </p>
            </div>
        {% endfor %}
    </div>
  </div>
  {% if is_paginated %}
    {% include 'includes/paginator.html' %}
  {% endif %}
{%endblock%}

online_market/templates/shop/index.html
{% extends 'base.html' %}
{%load static%}
{% block title %} Главная страница {% endblock %}
{%block content%}
<div class="index_page">
  <div class="index_title">
    Примеры изготовленных свечей
  </div>
  <div class="index_row">
  {% for image in image_for_example %}
    <div class="index_column">
      <img src="{{ image.image.url }}" alt="" class="border">
    </div>
  {%endfor%}
  </div>
  <div class="index_title">
    <a class="text" href = {% url 'shop:catalog'%}> Перейти в каталог </a>
  </div>
</div>
{%endblock%}

online_market/templates/shop/order_create.html
{% extends 'base.html' %}
{%load static%}
{% block title %} Заказ {% endblock %}
{% block content %}
<div class="index_page">
  {% if item_in_order|length < 1 %}
  <div class="order_title">
    <p>Вы ещё не начали оформлять заказ</p>
    <br><a href = {% url 'shop:catalog'%} class='nav__link'> вернуться к просмотру товаров </a>
    <p> Как только вы заполните корзину, вы сможете оформлять заказ </p>
  </div>
    {% else %}
    <div class="order__page">
  <div class="block1">
    <form action="." method="post">
      {% csrf_token %}
      {% for fields in form%}
        <br>{{fields.label}}
        <br>{{fields}}
      {% endfor %}
      <p> <button type="submit" class="button">
        Оформить заказ
  
      </button> </p>
    </form>
  </div>
  <div class="block2">
    <div class="order_title">
      Ваш заказ:
    </div>
    {% for item in item_in_order %}
      {% with product=item.product %}
      <div class="order_border">
        Название: {{ product.name }} 
        <br> Количество: {{ item.quantity }} шт.
        <br> Описание: {{product.description}}
        <br> Цена {{product.price}}
      </div>
      {% endwith %}
    {% endfor %}
    <p> Итоговая цена: {{ total_price }} рублей </p>
    <a href = {% url 'shop:catalog'%} class='detail_text'> Вернуться к просмотру товаров </a>
    <br><a href = {% url 'shop:cart_detail'%} class='detail_text'>Вернуться в корзину </a>
  </div>
</div>
</div>
{% endif %}
{% endblock %}

online_market/templates/shop/order_created.html
{% extends "base.html" %}

{% block title %}Thank you{% endblock %}

{% block content %}
<div class="order__final">
    <h1>Спасибо!</h1>
    <p>Ваш заказ оформлен!</p>
    <p> вы можете отслеживать его в личном кабинете <p>
</div>
{% endblock %}

online_market/templates/shop/order_detail.html
{% extends "base.html" %}
{% block title %}Заказ номер: {{current_order.id}} {% endblock %}
{% block content %}
{% for item in order_item%}
<div class="detail_order">
    <div class="detail__photo">
      <img src="{{ item.product.image.url }}" height='200'>
    </div>
    <br>{{ item.product.name }}
    <br>Описание: {{ item.product.description }}
    <br>Цена: {{ item.product.price }} рублей
  </div>
{%endfor%}
<center><h2><a href="{{ request.user.get_absolute_url }}">Вернуться назад</a></h2></center>
{% endblock %}

online_market/templates/shop/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Продукт {{product.name}}{% endblock %}
{% block content %}
  <div class="detail">
    <div class="detail__photo">
      <img src="{{ product.image.url }}">
    </div>
    <p class="name"> {{ product.name }} </p>
    <p> Описание: {{ product.description }}</p>
    <p class="price">Цена: {{ product.price }} рублей</p>
    {% if not request.user.is_authenticated %}
      <a href = {% url 'users:login'%} class='text'> Чтобы добавить товар в корзину, необходимо авторизоваться </a>
    {% else %}
    {% if product_in_cart %}
      <p>Товар уже в корзине
      <br><a href = {% url 'shop:cart_detail'%}>Перейти в корзину </a> </p>
    {% else %}
      <form action="{% url "shop:cart_add" product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <p><input type="submit" value="Добавить в корзину"></p>
      </form>
    {% endif %}
    {% endif %}
    <p class="back"><a href = {% url 'shop:catalog'%} class='detail_text'> Вернуться назад </a></p>
  </div>
{%endblock%}