online_market/online_market/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from users.urls import reset_password


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('', include(reset_password)),
    path('', include('users.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

online_market/shop/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static

from . import views

app_name = 'shop'

cart_path = [
    path('cart', views.CartView.as_view(), name='cart_detail'),
    path('add/<product_id>/',
         views.AddProductToCartView.as_view(), name='cart_add'),
    path('update/<product_id>/',
         views.CartProductQuantityUpdateView.as_view(), name='cart_update'),
    path('remove/<product_id>/',
         views.CartProductQuantityDecreaseView.as_view(), name='cart_remove'),
    path('cart/clear/', views.ClearCartView.as_view(), name='cart_clear'),
]

order_path = [
    path('order/create/', views.OrderCreateView.as_view(),
         name='order_create'),
    path('order/created/', views.OrderCreatedView.as_view(),
         name='order_created'),
    path('order/<order_id>/', views.OrderDetailView.as_view(),
         name='order_detail'),
]

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('catalog', views.CatalogView.as_view(), name='catalog'),
    path('product/<slug>/', views.ProductDetailView.as_view(),
         name='product_detail'),
    path('about_us', views.AboutUsView.as_view(), name='about_us'),
    path('', include(cart_path)),
    path('', include(order_path)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

online_market/users/urls.py
from django.contrib.auth.views import (LogoutView, PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)
from django.urls import include, path, reverse_lazy

from . import views

app_name = 'users'

reset_password = [
    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html'),
        name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete')
]

auth = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('register_done/', views.RegisterDone.as_view(), name='register_done'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
]

profile = [
    path('profile/<str:username>/', views.ProfileView.as_view(),
         name='profile'),
    path('profile/<str:username>/edit/', views.ProfileEditView.as_view(),
         name='profile_edit'),
]

urlpatterns = [
    path('', include(auth)),
    path('', include(profile)),
    path('reset_password/', include(reset_password)),
]

online_market/templates/includes/footer.html
<footer class="footer">
  <div class="google_maps">
    <iframe src="https://inlnk.ru/dn6l2n" width="285" height="150" style="border:0;" 
    allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
  </div>
</footer>

online_market/templates/includes/header.html
{%load static%}
<header class="header">
    <div class="header__inner">
      <div class="header__logo">
        <a href="/"> 
          <img src="{% static 'img/logotip.png' %}" alt=""> 
        </a>
      </div>
      <nav class="nav">
        {% if user.is_authenticated %}
          <a class="nav__link" href = {% url 'users:logout'%}> Выйти </a> 
          <a class="nav__link" href="{{ request.user.get_absolute_url }}"> Личный кабинет </a> 
          <a class="nav__link" href = {% url 'shop:cart_detail'%}> Корзина </a>
        {% else %}
          <a class="nav__link" href = {% url 'users:login'%}> Войти </a>
          <a class ="nav__link" href = {% url 'users:signup'%}> зарегистрироваться </a>
        {% endif %}
        <a class="nav__link" href ="/"> Главная страница </a> 
        <a class="nav__link" href ={% url 'shop:about_us'%}> О нас </a>
        <a class="nav__link" href = {% url 'shop:catalog'%}> Каталог </a>
      </nav>
  </div>
</header>

online_market/templates/includes/paginator.html
{% load static %}
{% if page_obj.has_other_pages %}
<div class="pagination">
  <nav aria-label="Page navigation" class="my-5">
    <div class="text">
    {% if page_obj.has_previous %}
        <a class="text" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая страница
        </a>
      </li>
    {% endif %}
    {% if page_obj.has_next %}
        <a class="text" href="?page={{ page_obj.next_page_number }}">
          Следующая страница
        </a>
      </li>
    {% endif %}    
    </div>
  </nav>
</div>
{% endif %}