online_market/online_market/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from users.urls import reset_password


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('', include(reset_password)),
    path('', include('users.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

online_market/shop/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static

from . import views

app_name = 'shop'

cart_path = [
    path('cart', views.CartView.as_view(), name='cart_detail'),
    path('add/<product_id>/',
         views.AddProductToCartView.as_view(), name='cart_add'),
    path('update/<product_id>/',
         views.CartProductQuantityUpdateView.as_view(), name='cart_update'),
    path('remove/<product_id>/',
         views.CartProductQuantityDecreaseView.as_view(), name='cart_remove'),
    path('cart/clear/', views.ClearCartView.as_view(), name='cart_clear'),
]

order_path = [
    path('order/create/', views.OrderCreateView.as_view(),
         name='order_create'),
    path('order/created/', views.OrderCreatedView.as_view(),
         name='order_created'),
    path('order/<order_id>/', views.OrderDetailView.as_view(),
         name='order_detail'),
]

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('catalog', views.CatalogView.as_view(), name='catalog'),
    path('product/<slug>/', views.ProductDetailView.as_view(),
         name='product_detail'),
    path('about_us', views.AboutUsView.as_view(), name='about_us'),
    path('', include(cart_path)),
    path('', include(order_path)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

online_market/users/urls.py
from django.contrib.auth.views import (LogoutView, PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)
from django.urls import include, path, reverse_lazy

from . import views

app_name = 'users'

reset_password = [
    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html'),
        name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete')
]

auth = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('register_done/', views.RegisterDone.as_view(), name='register_done'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
]

profile = [
    path('profile/<str:username>/', views.ProfileView.as_view(),
         name='profile'),
    path('profile/<str:username>/edit/', views.ProfileEditView.as_view(),
         name='profile_edit'),
]

urlpatterns = [
    path('', include(auth)),
    path('', include(profile)),
    path('reset_password/', include(reset_password)),
]

online_market/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class CustomUser(AbstractUser):
    """модель пользователя"""
    email = models.EmailField(max_length=254, unique=True,
                              verbose_name='Электронная почта')
    phone_number = models.CharField(max_length=15, default='')
    address = models.CharField(max_length=250, default='')
    postal_code = models.CharField(max_length=20, default='')
    city = models.CharField(max_length=100, default='')
    orders_count = models.IntegerField(default=0)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'
        index_together = (('id', 'username'),)

    def get_absolute_url(self):
        return reverse('users:profile',
                       args=[self.username])

    def __str__(self):
        return self.email

online_market/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.hashers import check_password
from django.core.validators import RegexValidator
from django.forms import (CharField, EmailField, EmailInput, ModelForm,
                          PasswordInput, TextInput, ValidationError)

from .models import CustomUser
from .validators import Min_Max_Length_Validator


class CreatingForm(UserCreationForm):
    """форма создания пользователя"""
    username = CharField(
        label='Логин',
        widget=TextInput(attrs={'placeholder': 'MyUserName'}),
        error_messages={'unique': 'Пользователь с таким логином '
                                  'уже существует'},
        validators=[RegexValidator(r'^[а-яА-ЯёЁa-zA-Z0-9]+$',
                                   'Недопустимые символы'),
                    Min_Max_Length_Validator])

    email = EmailField(
        label='Адрес электронной почты',
        widget=EmailInput(attrs={'placeholder': 'example@gmail.com'}),
        error_messages={
            'unique': 'Пользователь с такой почтой уже существует',
            'invalid': 'Введите корректный адрес электронной почты'})

    password1 = CharField(
        label='Пароль',
        widget=PasswordInput(attrs={'placeholder': '12345678'}))

    password2 = CharField(
        label='Подтвердите пароль',
        widget=PasswordInput(attrs={'placeholder': '12345678'}))

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')

    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 != password2:
            raise ValidationError('Пароли не совпадают')
        return password2


class LoginForm(AuthenticationForm):
    """форма авторизации пользователя"""
    username = EmailField(
        label='Адрес электронной почты',
        widget=TextInput(attrs={'placeholder': 'example@gmail.com'}))

    password = CharField(
        label='Пароль',
        widget=PasswordInput(attrs={'placeholder': '12345678'}))

    def clean_password(self):
        password = self.cleaned_data['password']
        username = self.cleaned_data.get('username')
        user = CustomUser.objects.filter(email=username).first()
        if not user or not check_password(password, user.password):
            raise ValidationError('Неверный логин или пароль')
        return password


class UserProfileForm(ModelForm):
    """форма профиля пользователя"""
    first_name = CharField(
        label='Имя',
        required=False,
        widget=TextInput(attrs={'placeholder': 'Иван'}),
        validators=[RegexValidator(r'^[а-яА-ЯёЁa-zA-Z]+$',
                                   'Недопустимые символы'),
                    Min_Max_Length_Validator])

    last_name = CharField(
        label='Фамилия',
        required=False,
        widget=TextInput(attrs={'placeholder': 'Иванов'}),
        validators=[RegexValidator(r'^[а-яА-ЯёЁa-zA-Z]+$',
                                   'Недопустимые символы'),
                    Min_Max_Length_Validator])

    phone_number = CharField(
        label='Номер телефона',
        required=False,
        widget=TextInput(attrs={'placeholder': '+79781234567'}),
        validators=[RegexValidator(r'^\+?1?\d{10,15}$',
                                   'Введите номер телефона '
                                   'в формате "+79781234567"')])
    city = CharField(
        label='Город',
        required=False,
        max_length=50,
        widget=TextInput(attrs={'placeholder': 'Москва'}))

    address = CharField(
        label='Адрес',
        required=False,
        max_length=50,
        widget=TextInput(attrs={'placeholder': 'Красная площадь'}))

    postal_code = CharField(
        label='Почтовый индекс',
        required=False,
        max_length=6,
        widget=TextInput(attrs={'placeholder': '230035'}))

    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'phone_number',
                  'city', 'address', 'postal_code')

online_market/users/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView
from django.views.generic.base import TemplateView

from .forms import CreatingForm, LoginForm, UserProfileForm
from .models import CustomUser


class SignUp(CreateView):
    template_name = 'users/signup.html'
    form_class = CreatingForm
    success_url = reverse_lazy('users:register_done')


class RegisterDone(TemplateView):
    template_name = 'users/register_done.html'


class LoginUserView(LoginView):
    template_name = 'users/login.html'
    form_class = LoginForm
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('users:profile',
                            args=(self.request.user.username,))


class ProfileView(DetailView):
    model = CustomUser
    template_name = 'users/profile.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = CustomUser.objects.prefetch_related('orders')
    paginate_by = settings.PRODUCT_COUNT

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_anonymous:
            return redirect(reverse('users:login'))
        if self.request.user.username != self.kwargs['username']:
            return redirect(reverse('users:profile',
                                    args=(request.user.username,)))
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        orders = self.request.user.orders.all()
        context['order'] = orders
        return context


class ProfileEditView(LoginRequiredMixin, UpdateView):
    model = CustomUser
    template_name = 'users/profile_edit.html'
    form_class = UserProfileForm
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_queryset(self):
        return CustomUser.objects.filter(email=self.request.user.email)

    def get_success_url(self):
        return reverse_lazy('users:profile',
                            args=(self.request.user.username,))

online_market/templates/users/logged_out.html
{% extends "base.html" %}
{% load static %}
{% block title %} Выход из личного кабинета {% endblock %}
{% block content %}
<div class="logout_detail">
  <div class="index_title">
    Вы успешно вышли из личного кабинета
  </div>
</div>
{% endblock %}

online_market/templates/users/login.html
{% extends "base.html" %}
{%load static%}
{% block title %} Войти {% endblock %}
{% block content %}
<form method="post">
  {% csrf_token %}
  <div class="login_title">
    <div class="login">
        <br>{{form.username.label}}
        <br>{{form.username}}
        {% if form.username.errors %}
          <br>{{ form.username.errors }}
        {% endif %}
        <br>{{form.password.label}}
        <br>{{form.password}}
        {% if form.password.errors %}
        <br>{{ form.password.errors }}
      {% endif %}
    <br><p> <button type="submit" class="button">
      Войти
    </button> </p>
    <p class="reset_pass"><a href="{% url "users:password_reset" %}"> Забыли пароль?</a> </p>
    </div>
  </div>
</form>
{% endblock %}

online_market/templates/users/password_reset_done.html
{% extends "base.html" %}

{% block title %}Reset your password{% endblock %}

{% block content %}
    <h1>Reset your password</h1>
    <p>We've emailed you instructions for setting your password.</p>
    <p>If you don't receive an email, please make sure you've entered the address you registered with.</p>
{% endblock %}

online_market/templates/users/password_reset_form.html
{% extends "base.html" %}

{% block title %}Reset your password{% endblock %}

{% block content %}
    <h1>Forgotten your password?</h1>
    <p>Enter your e-mail address to obtain a new password.</p>
    <form action="." method="post">
        {{ form.as_p }}
        <p><input type="submit" value="Send e-mail"></p>
        {% csrf_token %}
    </form>
{% endblock %}

online_market/templates/users/profile.html
{% extends 'base.html' %}
{%load static%}
{% block title %} Заказ {% endblock %}
{%block content%}

<div class="index_page">
  <div class="profile__page">
  <div class="block1">
    <br>Имя аккаунта: {{user.username}}
    {% if user.city|length == 0 and user.address|length  == 0 and user.postal_code|length == 0 and user.phone_number|length == 0 and user.first_name|length == 0 and user.last_name|length == 0 %}

    <br>Ваш профиль ещё не заполнен. <a href="{% url "users:profile_edit" request.user.username%} "> Заполнить? </a>
    {%else%}
    <br>Количество заказов пользователя {{user.orders_count}}
    <br> Имя: {{user.first_name}}
    <br> Фамилия: {{user.second_name}}
    <br> Номер телефона: {{user.phone_number}}
    <br> Город проживания: {{user.city}}
    <br> Адрес проживания: {{user.address}}
    <br> Индекс: {{user.postal_code}}
    <br><a href="{% url "users:profile_edit" request.user.username%} "> Желаете что-то изменить?</a>
    {%endif%}
  </div>
  <div class="block2">
      <div class="order_border">
        <center> <h3> История заказов: </h3> </center>
        {% for order in order%}
          <br> Заказ номер: <a href="{{ order.get_absolute_url }}"> {{order.id}}</a> | статус заказа: {{order.order_status}}
        {% endfor %}
      </div>

  </div>
</div>
</div>
{% endblock %}

online_market/templates/users/profile_edit.html
{% extends "base.html" %}
{%load static%}
{% block title %} Войти {% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="login_title">
      <div class="login">
        {{form.as_p}}
        <br><p> <button type="submit" class="button">
            Сохранить
          </button> </p>
      </div>
    </div>
</form>
{% endblock %}

online_market/templates/users/register_done.html
{% extends 'base.html' %}
{%load static%}
{% block title %} Главная страница {% endblock %}
{%block content%}
<div class="index_page">
  <div class="index_title">
    <p> Вы успешно зарегистрировались </p>
    <button type="submit" class="button">
      <a href="{% url "users:login"%}"> Войти?</a>
    </button>
  </div>
{% endblock %}

online_market/templates/users/signup.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Регистрация {% endblock %}
{% block content %}
  <form method="post">
    <div class="login_title">
      <div class="signup">
        {% csrf_token %}
        {%for fields in form%}

        <br> {{fields.label}}
        <br> {{fields}}
        {{fields.errors}}
        {% endfor %}
        <br><p> <input type="submit" class="button"value="Зарегистрироваться" href="{% url "users:register_done" %}"> </p>
      </div>
    </div>
  </form>
{% endblock %}

online_market/templates/users/verify_email_message.html
{% autoescape off %}
Ссылка для подтверждения пароля:
{{ protocol }}://{{ domain }}{% url 'email_verification' uidb64=uid token=token %}


{% endautoescape %}